package `in`.vedicpanchang.app.ui.theme

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.googlefonts.Font
import androidx.compose.ui.text.googlefonts.GoogleFont
import androidx.compose.ui.unit.sp
import `in`.vedicpanchang.app.R

// ── Google Fonts provider ──────────────────────────────────────────────────────
// Requires res/values/font_certs.xml — generated by Android Studio > Tools > Downloadable Fonts
val googleFontProvider = GoogleFont.Provider(
    providerAuthority = "com.google.android.gms.fonts",
    providerPackage = "com.google.android.gms",
    certificates = R.array.com_google_android_gms_fonts_certs
)

private val cinzelFont  = GoogleFont("Cinzel")
private val interFont   = GoogleFont("Inter")
private val monoFont    = GoogleFont("JetBrains Mono")

val CinzelFamily = FontFamily(
    Font(googleFont = cinzelFont, fontProvider = googleFontProvider, weight = FontWeight.Normal),
    Font(googleFont = cinzelFont, fontProvider = googleFontProvider, weight = FontWeight.SemiBold),
    Font(googleFont = cinzelFont, fontProvider = googleFontProvider, weight = FontWeight.Bold),
)

val InterFamily = FontFamily(
    Font(googleFont = interFont, fontProvider = googleFontProvider, weight = FontWeight.Normal),
    Font(googleFont = interFont, fontProvider = googleFontProvider, weight = FontWeight.Medium),
    Font(googleFont = interFont, fontProvider = googleFontProvider, weight = FontWeight.SemiBold),
    Font(googleFont = interFont, fontProvider = googleFontProvider, weight = FontWeight.Bold),
)

val MonoFamily = FontFamily(
    Font(googleFont = monoFont, fontProvider = googleFontProvider, weight = FontWeight.Normal),
    Font(googleFont = monoFont, fontProvider = googleFontProvider, weight = FontWeight.SemiBold),
    Font(googleFont = monoFont, fontProvider = googleFontProvider, weight = FontWeight.Bold),
)

// ── Text style definitions — mirrors app_text_styles.dart ─────────────────────

object AppTextStyles {

    val displayLarge = TextStyle(
        fontFamily = CinzelFamily, fontWeight = FontWeight.Bold,
        fontSize = 32.sp, letterSpacing = 1.2.sp
    )
    val displayMedium = TextStyle(
        fontFamily = CinzelFamily, fontWeight = FontWeight.Bold,
        fontSize = 24.sp, letterSpacing = 0.8.sp
    )
    val displaySmall = TextStyle(
        fontFamily = CinzelFamily, fontWeight = FontWeight.SemiBold,
        fontSize = 18.sp, letterSpacing = 0.5.sp
    )

    val bodyLarge = TextStyle(
        fontFamily = InterFamily, fontWeight = FontWeight.Normal, fontSize = 16.sp
    )
    val bodyMedium = TextStyle(
        fontFamily = InterFamily, fontWeight = FontWeight.Normal, fontSize = 14.sp
    )
    val bodySmall = TextStyle(
        fontFamily = InterFamily, fontWeight = FontWeight.Normal, fontSize = 12.sp
    )

    val labelLarge = TextStyle(
        fontFamily = InterFamily, fontWeight = FontWeight.SemiBold,
        fontSize = 14.sp, letterSpacing = 0.5.sp
    )
    val labelSmall = TextStyle(
        fontFamily = InterFamily, fontWeight = FontWeight.Medium,
        fontSize = 11.sp, letterSpacing = 0.8.sp
    )

    val timeLarge = TextStyle(
        fontFamily = MonoFamily, fontWeight = FontWeight.Bold,
        fontSize = 28.sp, letterSpacing = 2.sp
    )
    val timeMedium = TextStyle(
        fontFamily = MonoFamily, fontWeight = FontWeight.SemiBold,
        fontSize = 16.sp, letterSpacing = 1.sp
    )
    val timeSmall = TextStyle(
        fontFamily = MonoFamily, fontWeight = FontWeight.Normal,
        fontSize = 13.sp, letterSpacing = 0.5.sp
    )

    val saffronLabel = TextStyle(
        fontFamily = CinzelFamily, fontWeight = FontWeight.SemiBold,
        fontSize = 13.sp, color = AppColors.Primary, letterSpacing = 1.sp
    )
}
