package `in`.vedicpanchang.app.ui.horoscope

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import androidx.core.content.FileProvider
import `in`.vedicpanchang.app.data.model.HoroscopeModel
import `in`.vedicpanchang.app.l10n.HoroscopeLocalizer
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.time.Clock

fun shareKundaliImage(context: Context, bitmap: Bitmap) {
    val shareDir = File(context.cacheDir, "share").apply { mkdirs() }
    val file = File(shareDir, "kundali.png")
    file.outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }

    val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
    val intent = Intent(Intent.ACTION_SEND).apply {
        type = "image/png"
        putExtra(Intent.EXTRA_STREAM, uri)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    }
    context.startActivity(Intent.createChooser(intent, "Share Kundali"))
}

fun shareKundaliText(
    context: Context,
    chart: HoroscopeModel,
    localizer: HoroscopeLocalizer,
    locale: String
) {
    val now = Clock.System.now()
    val javaLocale = if (locale == "hi" || locale == "sa") Locale.forLanguageTag("hi-IN") else Locale.ENGLISH
    val birthDate = SimpleDateFormat("d MMM yyyy, HH:mm", javaLocale)
        .format(Date(chart.birthDetails.birthInstant.toEpochMilliseconds()))

    val sun = chart.planets.firstOrNull { it.name == "Sun" } ?: chart.planets.first()
    val moon = chart.planets.firstOrNull { it.name == "Moon" } ?: chart.planets.first()

    val currentMaha = chart.dashas.firstOrNull { now >= it.start && now < it.end }
    val currentAntar = currentMaha?.antardashas?.firstOrNull { now >= it.start && now < it.end }

    val text = buildString {
        appendLine("🕉  Vedic Kundali")
        appendLine("━━━━━━━━━━━━━━━━━━━━")
        appendLine("📅 $birthDate")
        appendLine("📍 ${chart.birthDetails.locationName}")
        appendLine()
        appendLine(
            "Lagna  : ${localizer.signNameFromEnglish(chart.lagnaSignName)} · ${
                chart.lagnaDegreeInSign.let {
                    "%.1f°".format(
                        it
                    )
                }
            } · ${localizer.nakshatraName(chart.lagnaNakshatraName)}"
        )
        appendLine(
            "☀️ Sun   : ${localizer.signNameFromEnglish(sun.signName)} · H${sun.houseNumber} · ${
                localizer.nakshatraName(
                    sun.nakshatraName
                )
            }"
        )
        appendLine(
            "🌙 Moon  : ${localizer.signNameFromEnglish(moon.signName)} · H${moon.houseNumber} · ${
                localizer.nakshatraName(
                    moon.nakshatraName
                )
            }"
        )
        appendLine()
        if (currentMaha != null) {
            appendLine("🪐 Current Dasha")
            appendLine(
                "   ${localizer.planetName(currentMaha.planet)} Mahadasha (ends ${
                    currentMaha.end.let {
                        formatShareDate(
                            it
                        )
                    }
                })"
            )
            if (currentAntar != null) {
                appendLine(
                    "   ${localizer.planetName(currentAntar.planet)} Antardasha (ends ${
                        formatShareDate(
                            currentAntar.end
                        )
                    })"
                )
            }
            appendLine()
        }
        appendLine("Navagraha Positions")
        appendLine("─────────────────────")
        chart.planets.forEach { p ->
            val retro = if (p.isRetrograde) " (R)" else ""
            appendLine(
                "${p.symbol} ${
                    localizer.planetName(p.name).padEnd(10)
                }${
                    localizer.signNameFromEnglish(p.signName).padEnd(14)
                }H${p.houseNumber}  ${p.degreeStr}$retro"
            )
        }
        appendLine()
        appendLine("Generated by Vedic Panchang")
    }

    val intent = Intent(Intent.ACTION_SEND).apply {
        type = "text/plain"
        putExtra(Intent.EXTRA_TEXT, text)
    }
    context.startActivity(Intent.createChooser(intent, "Share Kundali"))
}

private fun formatShareDate(instant: kotlin.time.Instant): String =
    SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH)
        .format(Date(instant.toEpochMilliseconds()))
